name: osc
description: A simple Open Sound Control (OSC) protocol implementation for Dart.
version: 0.0.1
#homepage: https://www.example.com
#author: pquitslund <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  ansicolor: ^0.0.9
  test: ^0.12.0
